# https://gohugo.io/getting-started/configuration/

# Dirs
archetypeDir = "archetypes"
assetDir     = "assets"
contentDir   = "content"
dataDir      = "data"
publishDir   = "public"
themesDir    = "themes"

# Build
buildDrafts           = false
buildExpired          = false
buildFuture           = false
capitalizeListTitles  = false
cleanDestinationDir   = true
# disableKinds          = ["categories", "tags"]
metaDataFormat        = "toml"
preserveTaxonomyNames = true
refLinksErrorLevel    = "ERROR"
rssLimit              = 20
stepAnalysis          = true
summaryLength         = 80
templateMetrics       = true
templateMetricsHints  = true
timeout               = "30s"

# Robots and Metadata
canonifyURLs                         = false
disableAliases                       = false
disableHugoGeneratorInject           = false
disableLiveReload                    = false
disablePathToLower                   = false
enableEmoji                          = true
enableGitInfo                        = true
enableInlineShortcodes               = false
enableMissingTranslationPlaceholders = true
enableRobotsTXT                      = true
pluralizeListTitles                  = true
relativeURLs                         = true
removePathAccents                    = true

# Language and TZ
defaultContentLanguage         = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage                 = false
languageCode                   = "en-US"
timeZone                       = "US/Mountain"

# Other
footnoteAnchorPrefix       = ""
footnoteReturnLinkContents = "â†©"
gc                         = true
googleAnalytics            = ""
ignoreCache                = false
ignoreLogs                 = false
ignoreVendorPaths          = false
log                        = true
pagination.pagerSize       = 10
pagination.path            = "p"
printI18nWarnings          = true
printPathWarnings          = true
printUnusedTemplates       = false
theme                      = "dst2024"
title                      = "DevSec Tools"
titleCaseStyle             = "AP"                      # https://gohugo.io/getting-started/configuration/#configure-title-case
toc                        = true
uglyURLs                   = false
watch                      = true

# Special
_merge = "deep"
